general:
  # auth:
  #   default: sumologic
  s3_regional_buckets: true
project:
  name: quickstart-sumo-logic-log-centralization
  regions:
  - us-east-2

tests:
  default:
    template: ./templates/master.template.yaml
    regions:
    - us-east-2
    parameters:
      QSS3KeyPrefix: "quickstart-sumo-logic-log-centralization/"
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3BucketRegion: "$[taskcat_current_region]"
      Section1aSumoLogicDeployment: "us1"
      Section1bSumoLogicAccessID: ""
      Section1cSumoLogicAccessKey: ""
      Section1dSumoLogicOrganizationId: ""
      Section2CloudTrailCreateBucket: "Yes"
      Section4bVpcCreateBucket: "Yes"
      Section6bS3AuditCreateBucket: "Yes"
      Section7cSecurityHubCreateBucket: "Yes"
      Section8cWafCreateBucket: "Yes"
      Section11NFWCreateS3Bucket: "Yes"
      Section9cConfigCreateSNSTopic: "Yes"
      Section11NFWCreateS3Source: "No"
      Section11InstallNFWApp: "No"
