AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Template to setup the Amazon VPC Flow Logs, PCI Compliance For Amazon VPC Flow app with AWS and Sumo Logic resources for AWS Quick Start Solution."

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sumo Logic Deployment Configuration"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - SumoOrganizationId
          - RemoveSumoResourcesOnDeleteStack

      - Label:
          default: "App Details - Collector Configuration"
        Parameters:
          - InstallVpcApp
          - InstallPCIVpcApp
          - CollectorName

      - Label:
          default: "App Details - VPC Logs S3 Source Configuration"
        Parameters:
          - CreateS3Bucket
          - LogsS3BucketName
          - CreateS3Source
          - S3BucketLogsPathExpression
          - S3SourceName
          - S3SourceCategoryName
          - ExcludeRuleName
          - ExcludeRuleRegex

      - Label:
          default: "Auto Enable VPC Flow logs for VPC Resources"
          Parameters:
            - AutoEnableVpcFlowLogs
            - FilterExpression

      - Label:
          default: "AWS Quick Start configuration"
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - ParentStackName

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name"
      SumoAccessID:
        default: "Sumo Logic Access ID"
      SumoAccessKey:
        default: "Sumo Logic Access Key"
      SumoOrganizationId:
        default: "Sumo Logic Organization Id"
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"

      InstallVpcApp:
        default: "Install Sumo Logic Amazon VPC Flow Logs App"
      InstallPCIVpcApp:
        default: "Install Sumo Logic PCI Compliance For Amazon VPC Flow App"
      CollectorName:
        default: "Collector Name"

      CreateS3Bucket:
        default: "Create AWS S3 Bucket"
      LogsS3BucketName:
        default: "AWS S3 Bucket Name"
      CreateS3Source:
        default: "Create Sumo Logic Amazon S3 Logs Source"
      S3BucketLogsPathExpression:
        default: "Path Expression for the logs"
      S3SourceName:
        default: "Sumo Logic Amazon S3 Logs Source Name"
      S3SourceCategoryName:
        default: "Sumo Logic Amazon S3 Logs Source Category Name"
      ExcludeRuleName:
        default: "S3 Logs processing rule name"
      ExcludeRuleRegex:
        default: "Regex to filter logs"

      AutoEnableVpcFlowLogs:
        default: "Enable VPC Flow logs for Existing Resources"
      FilterExpression:
        default: "Provide Filter Regular Expression"

      QSS3BucketName:
        default: "Quick Start S3 bucket name"
      QSS3BucketRegion:
        default: "Quick Start S3 bucket region"
      QSS3KeyPrefix:
        default: "Quick Start S3 key prefix"

      ParentStackName:
        default: "If Any, Name of parent Stack"

Parameters:
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
      - in
      - fed
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
  SumoAccessID:
    Type: String
    Description: "The Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  SumoAccessKey:
    Type: String
    Description: "The Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  SumoOrganizationId:
    Description: "The Account Overview page displays information about your Sumo Logic organization. Used for IAM Role in Sumo Logic AWS Sources."
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Organization Id can not be empty."
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to true. Default is true.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String

  InstallVpcApp:
    Type: String
    Description: "Yes -> To Install Sumo Logic Amazon VPC Flow Logs in Sumo Logic for AWS Quick Start Solution.
                  No -> Skip Installation of the app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  InstallPCIVpcApp:
    Type: String
    Description: "Yes -> To Install PCI Compliance For Amazon VPC Flow App in Sumo Logic for AWS Quick Start Solution.
                  No -> Skip Installation of the app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  CollectorName:
    Type: String
    Description: Change the collector name to be created else default name will be used.
    Default: AWS-Vpc-Flow-Logs-Collector

  CreateS3Bucket:
    Type: String
    Description: "Yes - Create a new S3 bucket in AWS S3.
                  No - Use an existing S3 bucket from AWS S3 which has VPC Logs."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  LogsS3BucketName:
    Type: String
    Description: "Existing Bucket Name - Provide value if the Flag is set to No.
                  New Bucket Name - Provide a unique Bucket Name if the flag is set to Yes."
  CreateS3Source:
    Type: String
    Description: "Yes - to create Sumo Logic Amazon S3 Log Source with provided bucket Name.
                  No - to skip creation of the Sumo Logic Amazon S3 Log Source."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  S3BucketLogsPathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
    Default: "*"
  S3SourceName:
    Type: String
    Description: Change the Sumo Logic Amazon S3 Source name to be created else default name will be used.
    Default: AWS-Vpc-Flow-Logs-Source
  S3SourceCategoryName:
    Type: String
    Description: "Existing - Change to an existing Source Category from Sumo Logic if Amazon S3 Source is not created.
                  New - Default will be used if Amazon S3 Source is Created."
    Default: AWS/Vpc/Flow/Logs
  ExcludeRuleName:
    Type: String
    Description: "Provide a Processing rule name for Amazon S3 Source."
    Default: "Exclude VPC File Flow headers"
  ExcludeRuleRegex:
    Type: String
    Description: "Enter a regex to match the log format to filter the logs."
    Default: version account-id interface-id srcaddr dstaddr srcport dstport protocol packets bytes start end action log-status

  AutoEnableVpcFlowLogs:
    Type: String
    Description: "Yes - to enable VPC Flow logs for existing resources in the region.
                  No - to skip VPC Flow logs for existing buckets."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  FilterExpression:
    Type: String
    Default: ""
    Description: "Empty means all resources. Provide regular expression for matching aws resources. For eg;- 'VpcId': 't1.micro.*?'|'NetworkInterfaceId': 'Test.*?']|'SubnetId': 'prod.*?'|test|prod'"

  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "aws-quickstart"
    Description: "S3 bucket name for the Quick Start assets. This string can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"
  QSS3BucketRegion:
    Default: "us-east-1"
    Description: "The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value."
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "quickstart-sumo-logic-log-centralization/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"

  ParentStackName:
    Type: String
    Default: "ParentStackName"
    Description: Parent Stack Name. Do Not Edit the value.

Conditions:
  do_not_use_parent_stack: !Equals [ !Ref ParentStackName, "ParentStackName"]
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']

  install_vpc_app: !Equals [!Ref InstallVpcApp, 'Yes']
  install_pci_vpc_app: !Equals [!Ref InstallPCIVpcApp, 'Yes']
  create_target_s3_bucket: !Equals [!Ref CreateS3Bucket, 'Yes']
  install_s3_source: !Equals [!Ref CreateS3Source, 'Yes']

  auto_enable_vpc_logging: !Equals [!Ref AutoEnableVpcFlowLogs, 'Yes']

  create_sns_topic: !And
    - !Condition do_not_use_parent_stack
    - !Condition install_s3_source

Resources:
  SumoLogicHelperRole:
    Type: AWS::IAM::Role
    Condition: do_not_use_parent_stack
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - cloudtrail:CreateTrail
                  - cloudtrail:DeleteTrail
                  - cloudtrail:UpdateTrail
                  - cloudtrail:StartLogging
                  - ec2:Describe*
                  - ec2:DeleteFlowLogs
                  - ec2:CreateFlowLogs
                  - ec2:DescribeFlowLogs
                  - logs:CreateLogDelivery
                  - logs:DeleteLogDelivery
                  - s3:GetBucketPolicy
                  - s3:PutBucketPolicy
                Resource: '*'

  SumoLogicHelperFunction:
    Type: 'AWS::Serverless::Function'
    DependsOn: SumoLogicHelperRole
    Condition: do_not_use_parent_stack
    Properties:
      Handler: main.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !Sub
          - "${S3Bucket}"
          - S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
        Key: !Sub "${QSS3KeyPrefix}submodules/sumo-aws-apps/sumologic-app-utils/sumo_app_utils.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - SumoLogicHelperRole
          - Arn

  SumoRole:
    Type: AWS::IAM::Role
    Condition: do_not_use_parent_stack
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::926226587429:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub "${SumoDeployment}:${SumoOrganizationId}"
      Path: "/"
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucketVersions
                  - s3:ListBucket
                Resource:
                  "*"

  SumoSNSTopic:
    Condition: create_sns_topic
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Sub "SumoSNSTopic-${AWS::StackName}"

  SumoSNSSubscription:
    Condition: install_s3_source
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !If
        - create_sns_topic
        - !Ref SumoSNSTopic
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SNSTopicArn'
      Endpoint: !GetAtt SumoS3Source.SUMO_ENDPOINT
      Protocol: https
      DeliveryPolicy:
        healthyRetryPolicy:
          numRetries: 40
          minDelayTarget: 10
          maxDelayTarget: 300
          numMinDelayRetries: 3
          numMaxDelayRetries: 5
          numNoDelayRetries: 0
          backoffFunction: exponential

  SumoSNSpolicy:
    Condition: create_sns_topic
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Id: SumoTopicPolicy
        Statement:
          - Action:
              - sns:Publish
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref "AWS::AccountId"
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::${LogsS3BucketName}"
            Effect: Allow
            Principal:
              AWS: "*"
            Resource:
              - !Ref SumoSNSTopic
      Topics:
        - Ref: SumoSNSTopic

  TargetS3Bucket:
    Condition: create_target_s3_bucket
    Type: AWS::S3::Bucket
    DependsOn:
      - SumoSNSpolicy
    Properties:
      BucketName: !Ref LogsS3BucketName
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:Put
            Topic: !Ref SumoSNSTopic

  SumoHostedCollector:
    Type: Custom::Collector
    Condition: install_s3_source
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      CollectorName: !Ref CollectorName
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoS3Source:
    Type: Custom::AWSSource
    Condition: install_s3_source
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      SourceType: AwsS3Bucket
      Region: !Ref "AWS::Region"
      SourceName: !Ref S3SourceName
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceCategory: !Ref S3SourceCategoryName
      CollectorId: !GetAtt SumoHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      TargetBucketName: !Ref LogsS3BucketName
      PathExpression: !Ref S3BucketLogsPathExpression
      filters:
        - filterType: "Exclude"
          name: !Ref ExcludeRuleName
          regexp: !Ref ExcludeRuleRegex
      RoleArn: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoRole
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoSourceRoleARN'
      multilineProcessingEnabled: false
      useAutolineMatching": false

  SumoVPCFlowLogApp:
    Type: Custom::App
    Condition: install_vpc_app
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      Region: !Ref "AWS::Region"
      AppName: "Amazon QuickStart - Amazon VPC Flow Logs"
      AppId: "3546d789-3a45-48df-ac85-6838044d988d"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        vpcFlowLogs: !Sub "_sourceCategory=${S3SourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoPCIVPCFlowLogApp:
    Type: Custom::App
    Condition: install_pci_vpc_app
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      Region: !Ref "AWS::Region"
      AppName: "Amazon QuickStart - PCI Compliance For Amazon VPC Flow"
      AppId: "afc4bae8-59af-41c0-b07d-c972400423e7"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        AppLogSource: !Sub "_sourceCategory=${S3SourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  EnableVpcFlowLogsResources:
    Type: Custom::EnableS3LogsResources
    Condition: auto_enable_vpc_logging
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AWSResource: vpc
      BucketName: !Ref LogsS3BucketName
      Filter: !Ref FilterExpression
      BucketPrefix: !Sub "VPC-FLOW-LOGS"
      AccountID: !Ref "AWS::AccountId"

Outputs:
  SumoRoleArn:
    Description: ARN of the cretaed Role.
    Condition: do_not_use_parent_stack
    Value: !GetAtt SumoRole.Arn

  SumoEndpoint:
    Description: SNS Subscription Endpoint
    Condition: install_s3_source
    Value: !GetAtt SumoS3Source.SUMO_ENDPOINT

