AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the Delivery KMS Key

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: KMS Key Attributes
        Parameters:
          - DeliveryKeyAlias
          - OrgPrimaryAccountId
          - LoggingAccountId

    ParameterLabels:
      DeliveryKeyAlias:
        default: Delivery KMS Key Alias
      OrgPrimaryAccountId:
        default: Organization Primary Account ID
      LoggingAccountId:
        default: Security Log Archive Account ID

Parameters:
  DeliveryKeyAlias:
    Type: String
    Description: Delivery KMS Key Alias
    Default: DeliveryKMSKey

  OrgPrimaryAccountId:
    Type: String
    Description: Organization primary account ID

  LoggingAccountId:
    Type: String
    Description: Organization log archive account ID


Resources:
  rDeliveryKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Delivery KMS Key
      EnableKeyRotation: True
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Sub ${DeliveryKeyAlias}
        Statement:
          - Action: "kms:*"
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Resource: "*"
            Sid: Enable IAM User Permissions

          - Action: kms:GenerateDataKey
            Effect: Allow
            Principal:
              Service: guardduty.amazonaws.com
            Resource: "*"
            Sid: Allow GuardDuty to encrypt logs

          - Action: kms:CreateAlias
            Condition:
              StringEquals:
                "kms:CallerAccount": !Sub ${AWS::AccountId}
                "kms:ViaService": cloudformation.us-east-1.amazonaws.com
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Resource: "*"
            Sid: Allow alias creation during setup

          - Action: kms:Decrypt
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${LoggingAccountId}:root
                - !Sub arn:${AWS::Partition}:iam::${OrgPrimaryAccountId}:root
            Resource: "*"
            Sid: Allow Log Archive and Primary account access

          - Action:
              - kms:DescribeKey
              - kms:Decrypt
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Resource: "*"
            Sid: Allow account access

  rDeliveryKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${DeliveryKeyAlias}
      TargetKeyId:
        !Ref rDeliveryKey

Outputs:
  oDeliveryKeyArn:
    Description: Delivery KMS Key ARN
    Value: !GetAtt rDeliveryKey.Arn