AWSTemplateFormatVersion: '2010-09-09'
Description: "Template to Configure the Execution Role to enable use of your account as a target account in AWS CloudFormation StackSets."
Parameters:
  ManagementAccountID:
    Type: String
    Description: AWS Account Id of the administrator account (the account in which StackSets will be created).
    MaxLength: 12
    MinLength: 12
  ExecutionRoleRuleName:
    Type: String
    Default: AWSCloudFormationStackSetExecutionRole
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ExecutionRoleRuleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref ManagementAccountID
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess