AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A CloudFormation template that creates the required AWS resources for Sumo Logic App -- Payment Card Industry (PCI) Compliance for AWS CloudTrail App.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Sumo Logic Deployment Configuration"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
      -
        Label:
          default: "Sumo Logic Collector and Source Configuration"
        Parameters:
          - CollectorName
          - SourceName
          - SourceCategory
          - PathExpression
          - ExternalID
          - PCICloudTrailAppSourceCategory
          - CreateTrail
      -
        Label:
          default: "S3 Configuration"
        Parameters:
          - LogsTargetS3BucketName
          - CreateTargetS3Bucket

      - Label:
          default: "AWS Quick Start configuration"
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix

    ParameterLabels:
      SumoDeployment:
        default: "Deployment Name"
      SumoAccessID:
        default: "Access ID"
      SumoAccessKey:
        default: "Access Key"
      CollectorName:
        default: "Collector Name"
      SourceName:
        default: "Source Name"
      SourceCategory:
        default: "Source Category"
      PathExpression:
        default: "Path Expression"
      
      RemoveSumoResourcesOnDeleteStack:
        default: "Remove Sumo Resources On Delete Stack"
      ExternalID:
        default: "IAM Role ExternalID"
      LogsTargetS3BucketName:
        default: "Target BucketName"
      CreateTargetS3Bucket:
        default: "Do you want to create a target S3 bucket?"
      QSS3BucketName:
        default: "Quick Start S3 bucket name"
      QSS3KeyPrefix:
        default: "Quick Start S3 key prefix"
      CreateTrail:
        default: "Create cloud trail"

Parameters:
  CollectorName:
    Type: String
    Default: PCIVPCCollector
  SourceName:
    Type: String
    Default: PCIVPCSource
  SourceCategory:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
  SumoAccessID:
    Type: String
  SumoAccessKey:
    Type: String
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1"
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: false
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is false.
    Type: String
  ExternalID:
    Type: String
    Description: An ID used in the trust policy to designate who can assume the role, formatted as deployment:accountId. Eg. us1:0000000000000131
  LogsTargetS3BucketName:
    Type: String
    Description: S3 access logs target buket name.
  CreateTargetS3Bucket:
    Type: String
    Default: "no"
    AllowedValues: ["yes", "no"]
  PathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
  ExcludeRuleName:
    Type: String
    Default: Exclude VPC File Flow headers
  ExcludeRule:
    Type: String
    Description: Exclude rule regexp
    Default: version account-id interface-id srcaddr dstaddr srcport dstport protocol packets bytes start end action log-status
  PCICloudTrailAppSourceCategory:
    Type: String
  S3SourceUtilTempalteS3Url:
    Type: String
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "aws-quickstart"
    Description: "S3 bucket name for the Quick Start assets. This string can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "quickstart-sumo-logic-log-centralization/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"
  CreateTrail:
    Type: String
    Default: "no"
    AllowedValues: ["yes", "no"]


Conditions:
  CreateBucket: !Equals [ !Ref CreateTargetS3Bucket, "yes" ]

Resources:
  
  sumoCloudTrailSourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref S3SourceUtilTempalteS3Url
      Parameters:
        SumoDeployment: !Ref SumoDeployment
        SumoAccessID: !Ref SumoAccessID
        SumoAccessKey: !Ref SumoAccessKey
        RemoveSumoResourcesOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
        CollectorName: !Ref CollectorName
        SourceName: !Ref SourceName
        LogsTargetS3BucketName: !Ref LogsTargetS3BucketName
        CreateTargetS3Bucket: !Ref CreateTargetS3Bucket
        SourceCategory: !Ref SourceCategory
        PathExpression: !Ref PathExpression
        ExternalID: !Ref ExternalID
        MultilineProcessingEnabled: True
        SumoSourceType: AwsCloudTrail
        ExcludeRuleName: "None"
        ExcludeRule: "None"
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        CreateTrail: !Ref CreateBucket

  sumoAmazonS3AuditApp:
    Type: Custom::App
    Properties:
      ServiceToken: !GetAtt sumoCloudTrailSourceStack.Outputs.SumoAppUtilsArn
      Region: !Ref "AWS::Region"
      AppName: "PCI Compliance For AWS CloudTrail."
      AppId: "924d7e2a-a14a-4b11-8c91-133241be2a51"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        CloudtrailLogSrc: !Sub "_sourceCategory=${PCICloudTrailAppSourceCategory}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
