########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Creates and configures an Organization CloudTrail

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Organization CloudTrail Attributes
        Parameters:
          - pCloudTrailName
          - pCloudTrailS3BucketName
          - pCloudTrailS3KeyPrefix
          - pEnableDataEventsOnly
          - pEnableLambdaDataEvents
          - pEnableS3DataEvents
          - pOrganizationCloudTrailKMSKey
      -
        Label:
          default: Lambda Function Attributes
        Parameters:
          - pLambdaExecutionRoleName
          - pLambdaFunctionName

      -
        Label:
          default: CloudWatch Log Group Attributes
        Parameters:
          - pCreateCloudWatchLogGroup
          - pDefaultLogGroupRetention
          - pResourceNamePrefix
      -
        Label:
          default: Resource Tags
        Parameters:
          - pTagKey1
          - pTagValue1
      - Label:
          default: "AWS Quick Start configuration"
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix

    ParameterLabels:
      pCloudTrailName:
        default: CloudTrail Name
      pCloudTrailS3BucketName:
        default: CloudTrail S3 Bucket Name
      pCloudTrailS3KeyPrefix:
        default: CloudTrail S3 Key Prefix
      pCreateCloudWatchLogGroup:
        default: Create CloudWatch Log Group
      pDefaultLogGroupRetention:
        default: Default Log Group Retention
      pEnableDataEventsOnly:
        default: Enable Data Events Only
      pEnableLambdaDataEvents:
        default: Enable Lambda Data Events
      pEnableS3DataEvents:
        default: Enable S3 Data Events
      pLambdaFunctionName:
        default: Lambda Function Name
      pLambdaExecutionRoleName:
        default: Lambda Execution Role Name
        
      pOrganizationCloudTrailKMSKey:
        default: Organization CloudTrail KMS Key
      pResourceNamePrefix:
        default: Resource Name Prefix
      pTagKey1:
        default: Tag Key
      pTagValue1:
        default: Tag Value
      QSS3BucketName:
        default: "Quick Start S3 bucket name"
      QSS3KeyPrefix:
        default: "Quick Start S3 key prefix"

Parameters:
  pCloudTrailName:
    AllowedPattern: "^[A-Za-z0-9][a-zA-Z0-9-\\-_.]{2,127}$"
    ConstraintDescription:
      Contain only ASCII letters (a-z, A-Z), numbers (0-9), periods (.), underscores (_), or dashes (-)
      Start with a letter or number, and end with a letter or number
      Be between 3 and 128 characters
      Have no adjacent periods, underscores or dashes. Names like my-_namespace and my--namespace are invalid.
      Not be in IP address format (for example, 192.168.5.4)
    Default: organization-trail
    Description: CloudTrail name
    Type: String

  pCloudTrailS3BucketName:
    AllowedPattern: "^$|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription:
      S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Description: CloudTrail S3 Bucket Name
    Type: String

  pCloudTrailS3KeyPrefix:
    Default: CloudTrail
    Description: CloudTrail S3 Prefix (Optional)
    Type: String

  pCreateCloudWatchLogGroup:
    AllowedValues: [true, false]
    Default: true
    Description: Create CloudWatch Log Group for the CloudTrail
    Type: String

  pDefaultLogGroupRetention:
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Default: 14
    Description: Specifies the number of days you want to retain CloudTrail log events in the CloudWatch Logs
    Type: String

  pEnableDataEventsOnly:
    AllowedValues: [true, false]
    Default: false
    Description: Only Enable Cloud Trail Data Events
    Type: String

  pEnableLambdaDataEvents:
    AllowedValues: [true, false]
    Default: true
    Description: Enable Cloud Trail S3 Data Events for all buckets
    Type: String

  pEnableS3DataEvents:
    AllowedValues: [true, false]
    Default: true
    Description: Enable Cloud Trail S3 Data Events for all buckets
    Type: String

  pLambdaFunctionName:
    AllowedPattern: '^[\w-]{0,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [_, -]
    Description: Lambda function name
    Type: String
    Default: LambdaASPIN2

  pLambdaExecutionRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: cloudtrail-org-config-lambda
    Type: String


  pOrganizationCloudTrailKMSKey:
    AllowedPattern: '^arn:(aws[a-zA-Z-]*)?:kms:[a-z0-9-]+:\d{12}:key\/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$'
    ConstraintDescription: 'Key ARN example:  arn:aws:kms:us-east-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab'
    Description: KMS Key ARN to use for encrypting logs
    Type: String

  pResourceNamePrefix:
    Description: Resource name prefix used to identify resources created by the automation framework
    Type: String
    Default: aspin

  pTagKey1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters and cannot be prefixed with "aws:".
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-''
    Description: Tag key
    Type: String
    Default: sumo

  pTagValue1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters.
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-'
    Description: Tag key value
    Type: String
    Default: aspin
  ResourcePrefix:
    Type: String
    Description: "Resouce prefix for auto deployment"
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "aws-quickstart"
    Description: "S3 bucket name for the Quick Start assets. This string can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"

  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "quickstart-sumo-logic-log-centralization/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"



Conditions:
  cCreateCloudWatchLogGroup: !Equals [!Ref pCreateCloudWatchLogGroup, true]
  cCreateS3KeyPrefix: !Not [!Equals [!Ref pCloudTrailS3KeyPrefix, '']]



Resources:
  rCloudTrailLogGroupRole:
    Type: AWS::IAM::Role
    Condition: cCreateCloudWatchLogGroup
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Allow * in resource for log stream
          - id: W28
            reason: The role name is defined to identify automation resources
    Properties:
      RoleName: !Sub ${ResourcePrefix}-cloudtrail-cloudwatch-logs-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - cloudtrail.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: !Sub ${ResourcePrefix}-cloudtrail-cloudwatch-logs-${AWS::Region}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CreateLogStreamAndEvents
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${rCloudTrailLogGroup}:log-stream:*
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1

  rCloudTrailLogGroup:
    Type: AWS::Logs::LogGroup
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W84
            reason: No KMS Key Provided
    Condition: cCreateCloudWatchLogGroup
    Properties:
      RetentionInDays: !Ref pDefaultLogGroupRetention
      LogGroupName: !Sub "CloudTrail/${pCloudTrailName}-${ResourcePrefix}-${AWS::Region}"

  rLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W84
            reason: No KMS Key Provided
    DeletionPolicy: Retain
    Properties:
      RetentionInDays: !Ref pDefaultLogGroupRetention
      LogGroupName: !Sub "/aws/lambda/${pLambdaFunctionName}-${ResourcePrefix}-${AWS::Region}"

  rLambdaRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Allow * in resource when required
          - id: W28
            reason: The role name is provided
    Properties:
      RoleName: !Sub ${pLambdaExecutionRoleName}-${ResourcePrefix}-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: cloudtrail-org-policy-logs
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: CreateLogGroup
              Effect: Allow
              Action: logs:CreateLogGroup
              Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${rLambdaLogGroup}

            - Sid: CreateLogStreamAndEvents
              Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${rLambdaLogGroup}:log-stream:*

      - PolicyName: cloudtrail-org-policy-cloudtrail
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: AllowCloudTrail
              Effect: Allow
              Action:
                - cloudtrail:AddTags
                - cloudtrail:RemoveTags
                - cloudtrail:CreateTrail
                - cloudtrail:DeleteTrail
                - cloudtrail:GetEventSelectors
                - cloudtrail:PutEventSelectors
                - cloudtrail:StartLogging
                - cloudtrail:StopLogging
                - cloudtrail:UpdateTrail
              Resource: !Sub arn:${AWS::Partition}:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/*

      - PolicyName: cloudtrail-org-policy-organization
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: AllowOrganizationsAccess
              Effect: Allow
              Action:
                - organizations:DescribeOrganization
                - organizations:DisableAWSServiceAccess
                - organizations:EnableAWSServiceAccess
                - organizations:ListAWSServiceAccessForOrganization
                - organizations:ListAccounts
              Resource: "*"

      - PolicyName: cloudtrail-org-policy-iam
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: AllowReadIamActions
              Effect: Allow
              Action: iam:GetRole
              Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*

            - !If
              - cCreateCloudWatchLogGroup
              - Sid: AllowPassRoleForCWLogGroupRole
                Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt rCloudTrailLogGroupRole.Arn
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - cloudtrail.amazonaws.com
              - !Ref AWS::NoValue

            - Sid: AllowCreateDeleteServiceLinkedRole
              Effect: Allow
              Action:
                - iam:CreateServiceLinkedRole
                - iam:DeleteServiceLinkedRole
              Resource:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/aws-service-role/cloudtrail.amazonaws.com/AWSServiceRoleForCloudTrail*
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1

  rLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub "${pLambdaFunctionName}-${ResourcePrefix}-${AWS::Region}"
      Handler: main.handler
      Runtime: python3.8
      CodeUri:
        Bucket: !Sub
                - "${S3Bucket}"
                - S3Bucket: !Sub "${QSS3BucketName}-${AWS::Region}"
        Key: !Sub "${QSS3KeyPrefix}apps/sumo-aws-apps/sumologic-app-utils/sumo_app_utils.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - rLambdaRole
          - Arn

  rLambdaCustomResource:
    Type: Custom::AWSCloudTrailOrg
    Version: "1.0"
    Properties:
      ServiceToken: !GetAtt rLambdaFunction.Arn
      AWS_PARTITION: !Sub ${AWS::Partition}
      CLOUDTRAIL_NAME: !Sub "${pCloudTrailName}-${ResourcePrefix}-${AWS::Region}"
      CLOUDWATCH_LOG_GROUP_ARN: !If [cCreateCloudWatchLogGroup, !GetAtt rCloudTrailLogGroup.Arn, '']
      CLOUDWATCH_LOG_GROUP_ROLE_ARN: !If [cCreateCloudWatchLogGroup, !GetAtt rCloudTrailLogGroupRole.Arn, '']
      ENABLE_DATA_EVENTS_ONLY: !Ref pEnableDataEventsOnly
      ENABLE_LAMBDA_DATA_EVENTS: !Ref pEnableLambdaDataEvents
      ENABLE_S3_DATA_EVENTS: !Ref pEnableS3DataEvents
      KMS_KEY_ID: !Ref pOrganizationCloudTrailKMSKey
      S3_BUCKET_NAME: !Ref pCloudTrailS3BucketName
      S3_KEY_PREFIX: !If [cCreateS3KeyPrefix, !Ref pCloudTrailS3KeyPrefix, '']
      TAG_KEY1: !Ref pTagKey1
      TAG_VALUE1: !Ref pTagValue1