AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Template to setup the AWS CloudTrail, PCI Compliance For AWS CloudTrail, CIS AWS Foundations Benchmark, Sumo Cloud Security Monitoring and Analytics For AWS CloudTrail, Sumo Global Intelligence for AWS CloudTrail SecOps app with AWS and Sumo Logic resources for AWS Quick Start Solution."

Parameters:
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
      - in
      - fed
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
  SumoAccessID:
    Type: String
    Description: "The Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  SumoAccessKey:
    Type: String
    Description: "The Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true

  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to true. Default is true.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String

  CollectorID:
    Type: String
    Description: "ID of Sumo Hosted Collector"

  SumoRoleArn:
    Description: "ARN of Sumo Role that allow sumologic read data from s3 bucket"
    Type: String
  SecurityToolingAccountRegion:
    Description: "Region of Tooling Account"
    Type: String
  LogArchivingAccountRegion:
    Description: "Region of Logging Account"
    Type: String
  InstallCloudTrailApp:
    Type: String
    Description: "Yes -> To Install Sumo Logic AWS CloudTrail App in Sumo Logic for AWS Quick Start Solution.
                  No -> Skip Installation of the app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  InstallPCICloudTrailApp:
    Type: String
    Description: "Yes -> To Install PCI Compliance For AWS CloudTrail App in Sumo Logic for AWS Quick Start Solution.
                  No -> Skip Installation of the app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  InstallCISFoundationApp:
    Type: String
    Description: "Yes -> To Install CIS AWS Foundations Benchmark App in Sumo Logic for AWS Quick Start Solution.
                  No -> Skip Installation of the app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  InstallCloudTrailMonitoringAnalyticsApp:
    Type: String
    Description: "Yes -> To Install Amazon CloudTrail - Sumo Cloud Security Monitoring and Analytics App in Sumo Logic for AWS Quick Start Solution.
                  No -> Skip Installation of the app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  InstallCloudTrailSecOpsApp:
    Type: String
    Description: "Yes -> To Install Sumo Global Intelligence for AWS CloudTrail SecOps App in Sumo Logic for AWS Quick Start Solution.
                  No -> Skip Installation of the app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  CloudTrailLogsBucketName:
    Type: String
    Description: "Existing Bucket Name - Provide value if the Flag is set to No.
                  New Bucket Name - Provide a unique Bucket Name if the flag is set to Yes."
  CloudTrailBucketPathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
    Default: "CloudTrail/*"
  CloudTrailLogsSourceName:
    Type: String
    Description: Change the CloudTrail Source name to be created else default name will be used.
    Default: AWS-Cloudtrail-Log-Source
  CloudTrailCreateS3LogsSource:
    Type: String
    Description: "Yes: Create Sumo Logic S3 log source to collect CloudTrail logs.
                  No: Skip creation of the Sumo Logic S3 log source."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  CloudTrailLogsSourceCategoryName:
    Type: String
    Description: "Existing - Change to an existing Source Category from Sumo Logic if CloudTrail Source is not created.
                  New - Default will be used if CloudTrail Source is Created."
    Default: AWS/Cloudtrail/Logs
  SNSTopicArn:
    Type: String
    Description: "ARN of SNS Topic to listen event S3 Put Object and trigger to Sumo Logic"
  ResourcePrefix:
    Type: String
    Description: "Resource prefix for auto deployment"
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "aws-quickstart"
    Description: "S3 bucket name for the Quick Start assets. This string can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "quickstart-sumo-logic-log-centralization/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"



Conditions:
  install_cloudtrail_app: !Equals [!Ref InstallCloudTrailApp, 'Yes']
  install_pci_cloudtrail_app: !Equals [!Ref InstallPCICloudTrailApp, 'Yes']
  install_cis_foundation_app: !Equals [!Ref InstallCISFoundationApp, 'Yes']
  install_cloudtrail_monitoring_analytics_app: !Equals [!Ref InstallCloudTrailMonitoringAnalyticsApp,'Yes']
  install_cloudtrail_secops_app: !Equals [!Ref InstallCloudTrailSecOpsApp,'Yes']
  install_cloudtrail_logs_source: !Equals [!Ref CloudTrailCreateS3LogsSource, 'Yes']

Resources:
  SumoLogicHelperRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ResourcePrefix}-CloudTrail-SumoLogicHelperFunction:*"


  SumoLogicHelperFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub "${ResourcePrefix}-CloudTrail-SumoLogicHelperFunction"
      Handler: main.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !Sub
                - "${S3Bucket}"
                - S3Bucket: !Sub "${QSS3BucketName}-${AWS::Region}"
        Key: !Sub "${QSS3KeyPrefix}apps/sumo-aws-apps/sumologic-app-utils/sumo_app_utils.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - SumoLogicHelperRole
          - Arn


  sumoAppWaitHandle:
    Type: "AWS::CloudFormation::WaitConditionHandle"

  sumoCloudTrailAppWaitCondition:
    Condition: install_cloudtrail_app
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !Ref sumoAppWaitHandle
      Timeout: "5"
      Count: 0



  sumoCloudTrailApp:
    Type: Custom::App
    Condition: install_cloudtrail_app
    Properties:
      ServiceToken: !GetAtt SumoLogicHelperFunction.Arn
      Region: !Ref LogArchivingAccountRegion
      AppName: "Amazon QuickStart - AWS CloudTrail"
      AppId: "ceb7fac5-1137-4a04-a5b8-2e49190be3d4"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        logsrc: !Sub "_sourceCategory=${CloudTrailLogsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment


  sumoPCICloudTrailAppWaitCondition:
    Condition: install_pci_cloudtrail_app
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !Ref sumoAppWaitHandle
      Timeout: "15"
      Count: 0

  sumoPCICloudTrailApp:
    Type: Custom::App
    Condition: install_pci_cloudtrail_app
    Properties:
      ServiceToken: !GetAtt SumoLogicHelperFunction.Arn
      Region: !Ref LogArchivingAccountRegion
      AppName: "Amazon QuickStart - PCI Compliance For AWS CloudTrail."
      AppId: "924d7e2a-a14a-4b11-8c91-133241be2a51"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        CloudtrailLogSrc: !Sub "_sourceCategory=${CloudTrailLogsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment


  sumoCISFoundationsAppWaitCondition:
    Condition: install_cis_foundation_app
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !Ref sumoAppWaitHandle
      Timeout: "25"
      Count: 0


  sumoCISFoundationsApp:
    Type: Custom::App
    Condition: install_cis_foundation_app
    Properties:
      ServiceToken: !GetAtt SumoLogicHelperFunction.Arn
      Region: !Ref LogArchivingAccountRegion
      AppName: "Amazon QuickStart - CIS AWS Foundations Benchmark"
      AppId: "9f630fe6-9253-4700-bb7e-36afc97b8cb6"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        paramId123: !Sub "_sourceCategory=${CloudTrailLogsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  sumMonitoringAnalyticsAppWaitCondition:
    Condition: install_cloudtrail_monitoring_analytics_app
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !Ref sumoAppWaitHandle
      Timeout: "35"
      Count: 0

  sumMonitoringAnalyticsApp:
    Type: Custom::App
    Condition: install_cloudtrail_monitoring_analytics_app
    Properties:
      ServiceToken: !GetAtt SumoLogicHelperFunction.Arn
      Region: !Ref LogArchivingAccountRegion
      AppName: "Amazon QuickStart - Amazon CloudTrail - Cloud Security Monitoring and Analytics App"
      AppId: "a0ce63ad-ed4f-4ea2-967b-da2854c53aa9"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        logsrc: !Sub "_sourceCategory=${CloudTrailLogsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      
  sumSecOpsAppWaitCondition:
    Condition: install_cloudtrail_secops_app
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !Ref sumoAppWaitHandle
      Timeout: "45"
      Count: 0

  sumSecOpsApp:
    Type: Custom::App
    Condition: install_cloudtrail_secops_app
    Properties:
      ServiceToken: !GetAtt SumoLogicHelperFunction.Arn
      Region: !Ref LogArchivingAccountRegion
      AppName: "Amazon QuickStart - Global Intelligence for AWS CloudTrail SecOps"
      AppId: "570bdc0d-f824-4fcb-96b2-3230d4497180"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        seed: "%rnd%"
        source: !Sub "_sourceCategory=${CloudTrailLogsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment


  SumoSNSSubscription:
    Condition: install_cloudtrail_logs_source
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref SNSTopicArn
      Endpoint: !GetAtt SumoCloudTrailSource.SUMO_ENDPOINT
      Protocol: https
      Region: !Ref SecurityToolingAccountRegion
      DeliveryPolicy:
        healthyRetryPolicy:
          numRetries: 40
          minDelayTarget: 10
          maxDelayTarget: 300
          numMinDelayRetries: 3
          numMaxDelayRetries: 5
          numNoDelayRetries: 0
          backoffFunction: exponential


  SumoCloudTrailSource:
    Condition: install_cloudtrail_logs_source
    Type: Custom::AWSSource
    Properties:
      SourceType: AwsCloudTrailBucket
      ServiceToken: !GetAtt SumoLogicHelperFunction.Arn
      Region: !Ref LogArchivingAccountRegion
      SourceName: !Ref CloudTrailLogsSourceName
      TargetBucketName: !Ref CloudTrailLogsBucketName
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceCategory: !Ref CloudTrailLogsSourceCategoryName
      CollectorId: !Ref CollectorID
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      PathExpression: !Ref CloudTrailBucketPathExpression
      RoleArn: !Ref SumoRoleArn

Outputs:

  SumoEndpoint:
    Description: SNS Subscription Endpoint
    Condition: install_cloudtrail_logs_source
    Value: !GetAtt SumoCloudTrailSource.SUMO_ENDPOINT

  CloudTrailAppFolder:
    Description: "Folder Name"
    Condition: install_cloudtrail_app
    Value: !GetAtt sumoCloudTrailApp.APP_FOLDER_NAME
  PciCloudTrailAppFolder:
    Description: "Folder Name"
    Condition: install_pci_cloudtrail_app
    Value: !GetAtt sumoPCICloudTrailApp.APP_FOLDER_NAME
