This Quick Start deployment builds a new AWS environment consisting of the infrastructure resources required to provision applications to your Sumo Logic account and necessary resources to your AWS account. During the deployment, you can choose which applications y to install.

=== Step 1. Prepare your Sumo Logic account 

1.	If you don’t already have a Sumo Logic enterprise account, create one at https://sumologic.com by following the on-screen instructions.
2.	Create the https://help.sumologic.com/Manage/Security/Access-Keys#manage-your-access-keys-on-preferences-page[Access Key and Access ID^] from your Sumo Logic account. You need them to pass as parameters when you launch the Quick Start template in the next step.
3.	You also need to pass the Organization ID, which you can get from your Sumo Logic account in the Administration section under the Account tab.

+
NOTE: If you want to use the Threat Intel app but have not configured data 
collection, see https://help.sumologic.com/07Sumo-Logic-Apps/01Amazon_and_AWS/Threat_Intel_for_AWS[Threat Intel for AWS^]. If you already configured data collection, note 
the relevant Sumo Logic source category for your data. 

=== Step 2. Sign in to your AWS account

Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.

=== Step 3. Launch the Quick Start

.  Deploy Sumo Logic Security Integrations. Each deployment takes about 10 minutes to complete.
+

[cols="3,1"]
|===
^|https://fwd.aws/Nm69g[Deploy Sumo Logic Security Integrations^]
^|https://fwd.aws/MG4nr[View template^]
|===

.	Check the Region displayed in the upper-right corner of the navigation bar, and change it as necessary. This is where the infrastructure for the Sumo Logic app resources is built. 
.  On the *Create stack* page, keep the default setting for the template URL, then choose 
.  On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. 

When you finish reviewing and customizing the parameters, choose *Next*.

ifndef::production_build[]
_**This portion of the deployment guide is located at `docs/generated/parameters/index.adoc`**_
++++
<div class="preview_mode">
++++
endif::production_build[]
include::../generated/parameters/index.adoc[]
ifndef::production_build[]
++++
</div>
++++
endif::production_build[]