AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Organization GuardDuty delegated admin template for to setup the Amazon GuardDuty, Global Intelligence for Amazon GuardDuty with AWS and Sumo Logic resources for AWS Quick Start Solution.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sumo Logic Deployment Configuration"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack

      - Label:
          default: "App Details - Collector Configuration"
        Parameters:
          - InstallSumoGuardDutyApp
          - InstallSumoGlobalGuardDutyApp
          - CollectorID

      - Label:
          default: "App Details - HTTP Logs Source Configuration"
        Parameters:
          - CreateHttpLogsSource
          - HttpLogsSourceName
          - HttpLogsSourceCategoryName

      - Label:
          default: "AWS GuardDuty App Details - Configuration"
        Parameters:
          - InstallAWSGuardDutyApp
      - Label:
          default: AWS GuardDuty Attributes
        Parameters:
          - AutoEnableS3Logs
          - ConfigurationRoleName
          - DelegatedAdminAccountId
          - EnabledRegions
          - FindingPublishingFrequency
      - Label:
          default: AWS GuardDuty Lambda Function Attributes
        Parameters:
          - LambdaExecutionRoleName
          - OrganizationId
      - Label:
          default: AWS StackSet Attributes
        Parameters:
          - AdministrationRoleArn
          - ExecutionRoleRuleName
          - OrganizationRootID
      - Label:
          default: "AWS Quick Start configuration"
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - ParentStackName
          - ParentHelperFunctionArn

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name"
      SumoAccessID:
        default: "Sumo Logic Access ID"
      SumoAccessKey:
        default: "Sumo Logic Access Key"
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"
      InstallSumoGuardDutyApp:
        default: "Install Sumo Logic Amazon GuardDuty App"
      InstallSumoGlobalGuardDutyApp:
        default: "Install Sumo Logic Global Intelligence for Amazon GuardDuty"
      CollectorID:
        default: "ID of Hosted Collector"
      CreateHttpLogsSource:
        default: "Create Sumo Logic HTTP Logs Source"
      HttpLogsSourceName:
        default: "Sumo Logic HTTP Logs Source Name"
      HttpLogsSourceCategoryName:
        default: "Sumo Logic HTTP Logs Source Category Name" 

      InstallAWSGuardDutyApp:
        default: "Install AWS GuardDuty App"
      AutoEnableS3Logs:
        default: Auto Enable S3 Logs
      ConfigurationRoleName:
        default: Configuration Role Name
      DelegatedAdminAccountId:
        default: Delegated Admin Account ID
      EnabledRegions:
        default: Enabled Regions
      FindingPublishingFrequency:
        default: Finding Publishing Frequency
      LambdaExecutionRoleName:
        default: Lambda Execution Role Name        
      OrganizationId:
        default: Organization ID

      AdministrationRoleArn:
        default: Arn of Administration Role
      ExecutionRoleRuleName:
        default: Execution Role Name
      OrganizationRootID:
        default: "AWS Organization root ID"

      QSS3BucketName:
        default: "Quick Start S3 bucket name"
      QSS3BucketRegion:
        default: "Quick Start S3 bucket region"
      QSS3KeyPrefix:
        default: "Quick Start S3 key prefix"

      ParentStackName:
        default: "If Any, Name of parent Stack"
      ParentHelperFunctionArn:
        default: "If Any, Arn of parent Helper Function"

Parameters:
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
      - in
      - fed
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
    AllowedPattern: ".+"
    Default: "us2"
  SumoAccessID:
    Type: String
    Description: "The Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  SumoAccessKey:
    Type: String
    Description: "The Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: "To delete collector, sources and app when stack is deleted, set this parameter to true. Default is false.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String

  InstallSumoGuardDutyApp:
    Type: String
    Description: "Yes -> To Install Amazon GuardDuty App in Sumo Logic for AWS Quick Start Solution.
                  No -> Skip Installation of the app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  InstallSumoGlobalGuardDutyApp:
    Type: String
    Description: "Yes -> To Install Global Intelligence for Amazon GuardDuty in Sumo Logic for AWS Quick Start Solution.
                  No -> Skip Installation of the app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  CollectorID:
    Type: String
    Description: Change the collector id of Sumo Hosted Collector


  CreateHttpLogsSource:
    Type: String
    Description: "Choose Yes to create Sumo Logic HTTP logs source. Choose No if HTTP Logs source already exist."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  HttpLogsSourceName:
    Type: String
    Description: Change the HTTP Source name to be created else default name will be used.
    Default: AWS-GuardDuty-Source
  HttpLogsSourceCategoryName:
    Type: String
    Description: "Existing - Change to an existing Source Category from Sumo Logic if HTTP Source is not created.\n
                  New - Change the source category else Default will be used if HTTP Source is Created"
    Default: AWS/GuardDuty/logs

  InstallAWSGuardDutyApp:
    Type: String
    Description: "Yes -> To Install Amazon GuardDuty App in Sumo Logic for AWS Quick Start Solution.
                  No -> Skip Installation of the app."
    Default: 'No'
    AllowedValues:
      - 'Yes'
      - 'No'
  AutoEnableS3Logs:
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: Auto enable S3 logs
    Type: String

  ConfigurationRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Description: Configuration role to assume in the delegated administrator account
    Type: String

  DelegatedAdminAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Delegated administrator account ID
    Type: String

  EnabledRegions:
    Description: Comma delimited list of regions to enable GuardDuty. Leave blank to enable all regions.
    Type: String
    Default: "us-east-1, us-east-2"

  FindingPublishingFrequency:
    AllowedValues: [FIFTEEN_MINUTES, ONE_HOUR, SIX_HOURS]
    Default: FIFTEEN_MINUTES
    Description: Finding publishing frequency
    Type: String


  OrganizationId:
    AllowedPattern: '^o-[a-z0-9]{10,32}$'
    ConstraintDescription: >
      The Org Id must be a 12 character string starting with o- and followed by 10 lower case alphanumeric characters
    Description: AWS Organizations ID
    MaxLength: 12
    MinLength: 12
    Type: String

  LambdaExecutionRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: guardduty-org-lambda
    Type: String

  LogArchivingAccountRegion:
    Type: String
    Description: "Region of Logging Account"

  AdministrationRoleArn:
    Description: Arn of AWS Administration Role name to enable use of AWS CloudFormation StackSets.
    Type: String

  ExecutionRoleRuleName:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    Description: AWS Execution Role name of the administrator account (the account in which StackSets will be created).
    Type: String
    Default: AWSCloudFormationStackSetExecutionRole

  OrganizationRootID:
    AllowedPattern: '^r-[0-9a-z]{4,32}$'
    Description: >
      The Root ID string requires r- followed by from 4 to 32 lowercase letters or digits.
    MaxLength: 34
    Type: String

  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "aws-quickstart"
    Description: "S3 bucket name for the Quick Start assets. This string can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"
  QSS3BucketRegion:
    Default: "us-east-1"
    Description: "The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value."
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "quickstart-sumo-logic-log-centralization/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"

  ParentStackName:
    Type: String
    Default: "ParentStackName"
    Description: Parent Stack Name. Do Not Edit the value.

  ParentHelperFunctionArn:
    Type: String
    Default: "ParentHelperFunctionArn"
    Description: Parent Stack Name. Do Not Edit the value.    

Conditions:

  install_sumo_guardduty_app: !Equals [!Ref InstallSumoGuardDutyApp, 'Yes']
  install_aws_guardduty_app: !Equals [!Ref InstallAWSGuardDutyApp, 'Yes']
  install_sumo_global_guardduty_app: !Equals [!Ref InstallSumoGlobalGuardDutyApp, 'Yes']
  install_http_logs_source: !Equals [!Ref CreateHttpLogsSource, 'Yes']

Resources:
  rConfigurationRole:
    Condition: install_aws_guardduty_app
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Actions require * in resource
          - id: W28
            reason: Explicit role name provided
    Properties:
      RoleName: !Ref ConfigurationRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
      Path: "/"
      Policies:
        - PolicyName: guardduty-org-policy-organizations
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: organizations:ListAccounts
                Effect: Allow
                Resource: !Sub "arn:${AWS::Partition}:organizations:*:*:*"
                Sid: OrganizationsListAccounts

        - PolicyName: guardduty-org-policy-guardduty
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: guardduty:ListDetectors
                Effect: Allow
                Resource: !Sub "arn:${AWS::Partition}:guardduty:*:*:*"
                Sid: GuardDutyNoResource

              - Action:
                  - guardduty:CreateMembers
                  - guardduty:CreatePublishingDestination
                  - guardduty:DeleteDetector
                  - guardduty:DeleteMembers
                  - guardduty:DisassociateMembers
                  - guardduty:ListMembers
                  - guardduty:ListPublishingDestinations
                  - guardduty:UpdateDetector
                  - guardduty:UpdateMemberDetectors
                  - guardduty:UpdateOrganizationConfiguration
                  - guardduty:UpdatePublishingDestination
                Effect: Allow
                Resource:
                  - !Sub arn:${AWS::Partition}:guardduty:*:${AWS::AccountId}:/detector/*
                  - !Sub arn:${AWS::Partition}:guardduty:*:${AWS::AccountId}:detector/*
                Sid: GuardDutyWithResource

        - PolicyName: guardduty-org-policy-iam
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: iam:GetRole
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*
                Sid: AllowReadIamActions

              - Action:
                  - iam:CreateServiceLinkedRole
                  - iam:DeleteServiceLinkedRole
                Condition:
                  StringLike:
                    iam:AWSServiceName: guardduty.amazonaws.com
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/aws-service-role/guardduty.amazonaws.com/AWSServiceRoleForAmazonGuardDuty
                Sid: AllowCreateDeleteServiceLinkedRole

              - Action:
                  - iam:DeleteRolePolicy
                  - iam:PutRolePolicy
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/aws-service-role/guardduty.amazonaws.com/AWSServiceRoleForAmazonGuardDuty
                Sid: AllowPolicyActions

  GuardDutyDeleteDetectorRoleStackset:
    Condition: install_aws_guardduty_app
    Type: 'AWS::CloudFormation::StackSet'
    Properties:
      StackSetName: !Sub "GuardDuty-Delete-Detector-Role-${AWS::StackName}"
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - 'CAPABILITY_NAMED_IAM'
        - 'CAPABILITY_IAM'
        - 'CAPABILITY_AUTO_EXPAND' 
      StackInstancesGroup:
        - Regions:
            -  !Select [0, !Split [",", !Ref EnabledRegions]]
          DeploymentTargets:
              OrganizationalUnitIds: 
                - !Ref OrganizationRootID
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}apps/sumo-aws-apps/guardduty-org/guardduty-org-delete-detector-role.yaml'
        - S3Region: !Ref 'AWS::Region'
          S3Bucket: !Sub '${QSS3BucketName}-${AWS::Region}'
      AutoDeployment: 
        Enabled: true
        RetainStacksOnAccountRemoval: true
      Parameters: 
        - ParameterKey: 'DeleteDetectorRoleName'
          ParameterValue: !Sub 
            - "DeleteDetectorRole-${StackName}"
            - StackName: !Select [0, !Split ["-", !Ref "AWS::StackName"]]
        - ParameterKey: 'OrgPrimaryAccountId'
          ParameterValue: !Ref "AWS::AccountId"

  OrgSumoCloudWatchEventFunctionStackset:
    Condition: install_http_logs_source
    DependsOn:
      - "SumoHTTPSource"  
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: !Sub 'GuardDutyOrgCloudWatchEventFunction-${AWS::StackName}'
      AdministrationRoleARN: !Ref AdministrationRoleArn
      ExecutionRoleName: !Ref ExecutionRoleRuleName
      PermissionModel: SELF_MANAGED
      Capabilities:
        - 'CAPABILITY_NAMED_IAM'
        - 'CAPABILITY_IAM'
        - 'CAPABILITY_AUTO_EXPAND'
      StackInstancesGroup:
        - Regions: !Split [",", !Ref EnabledRegions]
          DeploymentTargets:
            Accounts:
              - !Ref AWS::AccountId
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}apps/sumo-aws-apps/guardduty-org/guardduty-org-cloudwatch-event.yaml'
        - S3Region:  !Ref 'AWS::Region'
          S3Bucket: !Sub '${QSS3BucketName}-${AWS::Region}'
      Parameters:
        - ParameterKey: 'SumoEndpoint'
          ParameterValue: !GetAtt SumoHTTPSource.SUMO_ENDPOINT
        - ParameterKey: 'QSS3BucketName'
          ParameterValue: !Ref QSS3BucketName
        - ParameterKey: 'QSS3BucketRegion'
          ParameterValue: !Ref QSS3BucketRegion
        - ParameterKey: 'QSS3KeyPrefix'
          ParameterValue: !Ref QSS3KeyPrefix

  rAWSGuardDutyCustomResource:
    Type: Custom::GuardDuty
    DependsOn:
      - "rConfigurationRole"
      - "GuardDutyDeleteDetectorRoleStackset"
    Condition: install_aws_guardduty_app
    Version: "1.0.1"
    Properties:
      ServiceToken: !Ref ParentHelperFunctionArn
      AUTO_ENABLE_S3_LOGS: !Ref AutoEnableS3Logs
      AWS_PARTITION: !Sub ${AWS::Partition}
      CONFIGURATION_ROLE_NAME: !Select [ 1, !Split ['/', !GetAtt rConfigurationRole.Arn]]
      DELEGATED_ADMIN_ACCOUNT_ID: !Ref DelegatedAdminAccountId
      DELETE_DETECTOR_ROLE_NAME: !Sub 
        - "DeleteDetectorRole-${StackName}"
        - StackName: !Select [0, !Split ["-", !Ref "AWS::StackName"]]
      ENABLED_REGIONS: !Ref EnabledRegions
      FINDING_PUBLISHING_FREQUENCY: !Ref FindingPublishingFrequency

  SumoHTTPSource:
    Condition: install_http_logs_source
    Type: Custom::HTTPSource
    Properties:
      ServiceToken: !Ref ParentHelperFunctionArn
      Region: !Ref LogArchivingAccountRegion
      SourceName: !Ref HttpLogsSourceName
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceCategory: !Ref HttpLogsSourceCategoryName
      CollectorId: !Ref CollectorID
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      DateFormat: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
      DateLocatorRegex: '.*"updatedAt":"(.*)".*'

  sumoGuardDutyApp:
    Type: Custom::App
    Condition: install_sumo_guardduty_app
    Properties:
      ServiceToken: !Ref ParentHelperFunctionArn
      Region: !Ref LogArchivingAccountRegion
      AppName: "Amazon QuickStart - Amazon GuardDuty"
      AppId: "5a58719f-0f8a-4aa7-993f-9cc337a286aa"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        logsrc: !Sub "_sourceCategory=${HttpLogsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  sumoGlobalGuardDutyApp:
    Type: Custom::App
    Condition: install_sumo_global_guardduty_app
    Properties:
      ServiceToken: !Ref ParentHelperFunctionArn
      Region: !Ref LogArchivingAccountRegion
      AppName: "Amazon QuickStart - Global Intelligence for Amazon GuardDuty"
      AppId: "8e7efcb3-040a-4a92-9f8d-922fafb24afb"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        gdbenchmark: !Sub "_sourceCategory=${HttpLogsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment