AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Template to setup the AWS Config app with AWS and Sumo Logic resources for AWS Quick Start Solution."

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sumo Logic Access Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack

      - Label:
          default: "App Details - Collector Configuration"
        Parameters:
          - InstallApp
          - CollectorName

      - Label:
          default: "App Details - AWS Config Details"
        Parameters:
          - EnableConfig
          - BucketName
          - CreateSNSTopic
          - TopicName

      - Label:
          default: "App Details - HTTP Logs Source Configuration"
        Parameters:
          - CreateHttpLogsSource
          - HttpLogsSourceName
          - HttpLogsSourceCategoryName

      - Label:
          default: "AWS Quick Start configuration"
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - ParentStackName

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name"
      SumoAccessID:
        default: "Sumo Logic Access ID"
      SumoAccessKey:
        default: "Sumo Logic Access Key"
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"

      InstallApp:
        default: "Install Sumo Logic App"
      CollectorName:
        default: "Collector Name"

      EnableConfig:
        default: "Enable AWS Config for the region"
      BucketName:
        default: "Bucket Name"
      CreateSNSTopic:
        default: "Create SNS Topic for logs delivery"
      TopicName:
        default: "Topic Name"

      CreateHttpLogsSource:
        default: "Create Sumo Logic HTTP Logs Source"
      HttpLogsSourceName:
        default: "Sumo Logic HTTP Logs Source Name"
      HttpLogsSourceCategoryName:
        default: "Sumo Logic HTTP Logs Source Category Name"

      QSS3BucketName:
        default: "Quick Start S3 bucket name"
      QSS3BucketRegion:
        default: "Quick Start S3 bucket region"
      QSS3KeyPrefix:
        default: "Quick Start S3 key prefix"

      ParentStackName:
        default: "If Any, Name of parent Stack"

Parameters:
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
      - in
      - fed
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
    AllowedPattern: ".+"
  SumoAccessID:
    Type: String
    Description: "The Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  SumoAccessKey:
    Type: String
    Description: "The Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: false
    Description: "To delete collector, sources and app when stack is deleted, set this parameter to true. Default is false.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String

  InstallApp:
    Type: String
    Description: "Yes -> To Install App in Sumo Logic for AWS Quick Start Solution.
                  No -> Skip Installation of the app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  CollectorName:
    Type: String
    Description: Change the collector name to be created else default name will be used.
    Default: AWS-Config-Collector

  EnableConfig:
    Type: String
    Description: "Choose Yes to enable config for the region.
                  Choose No if config is already enabled."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  BucketName:
    Type: String
    Description: "Enable config flag -> Yes. Provide a new bucket name to receive configuration history and configuration snapshot files."
    Default: ""
  CreateSNSTopic:
    Type: String
    Description: "Choose Yes to create SNS Topic and attach the SNS topic to AWS Config setting to deliver the logs.
                  Choose No if config logs are already delivered to an existing SNS topic."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  TopicName:
    Type: String
    Description: Required when flag -> No. Provide exisitng config SNS topic from Config settings to stream configuration changes and notifications.
    Default: ""

  CreateHttpLogsSource:
    Type: String
    Description: "Choose Yes to create Sumo Logic HTTP logs source. Choose No if HTTP Logs source already exist."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  HttpLogsSourceName:
    Type: String
    Description: Change the HTTP Source name to be created else default name will be used.
    Default: AWS-Config-Source
  HttpLogsSourceCategoryName:
    Type: String
    Description: "Existing - Change to an existing Source Category from Sumo Logic if HTTP Source is not created.\n
                  New - Change the source category else Default will be used if HTTP Source is Created"
    Default: AWS/config/logs

  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "aws-quickstart"
    Description: "S3 bucket name for the Quick Start assets. This string can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"
  QSS3BucketRegion:
    Default: "us-east-1"
    Description: "The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value."
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "quickstart-sumo-logic-log-centralization/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"

  ParentStackName:
    Type: String
    Default: "ParentStackName"
    Description: Parent Stack Name. Do Not Edit the value.

Conditions:
  do_not_use_parent_stack: !Equals [ !Ref ParentStackName, "ParentStackName"]
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']

  install_app: !Equals [!Ref InstallApp, 'Yes']
  create_sns_topic: !Equals [!Ref CreateSNSTopic, 'Yes']
  enable_config: !Equals [!Ref EnableConfig, 'Yes']
  install_http_logs_source: !Equals [!Ref CreateHttpLogsSource, 'Yes']

  create_bukcet: !And
    - !Condition enable_config
    - !Condition do_not_use_parent_stack

Resources:

  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Condition: enable_config
    Properties:
      Name: default
      RoleARN: !GetAtt [ConfigRole, Arn]

  ConfigRole:
    Type: AWS::IAM::Role
    Condition: enable_config
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [config.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AWSConfigRole']
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:GetBucketAcl
                Resource: !Join ['', ['arn:aws:s3:::', !Ref BucketName]]
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Join ['', ['arn:aws:s3:::', !Ref BucketName, /AWSLogs/,
                                      !Ref 'AWS::AccountId', /*]]
                Condition:
                  StringEquals:
                    s3:x-amz-acl: bucket-owner-full-control
              - Effect: Allow
                Action: config:Put*
                Resource: '*'

  SumoSNSTopic:
    Type: "AWS::SNS::Topic"
    Condition: create_sns_topic
    Properties:
      TopicName: !Sub "SumoSNSTopic-${AWS::StackName}"

  ConfigTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Condition: create_sns_topic
    Properties:
      PolicyDocument:
        Id: ConfigTopicPolicy
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: SNS:Publish
            Resource: '*'
      Topics: [!Ref 'SumoSNSTopic']

  WaitHandle:
    Type: "AWS::CloudFormation::WaitConditionHandle"

  EnableConfigWaitHandle:
    Condition: enable_config
    DependsOn: ConfigRole
    Type: "AWS::CloudFormation::WaitConditionHandle"

  EnableConfigWaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !If [enable_config, !Ref EnableConfigWaitHandle, !Ref WaitHandle]
      Timeout: "10"
      Count: 0

  DeliveryChannelWhenConfigIsTurnedOn:
    Type: "Custom::ConfigDeliveryChannel"
    Condition: create_sns_topic
    DependsOn: [ConfigTopicPolicy, EnableConfigWaitCondition]
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      DeliveryFrequency: Six_Hours
      S3BucketName: !If [enable_config, !Ref BucketName, ""]
      SnsTopicARN: !Ref SumoSNSTopic
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack

  SumoSNSSubscription:
    Type: "AWS::SNS::Subscription"
    Condition: install_http_logs_source
    Properties:
      TopicArn: !If
        - create_sns_topic
        - !Ref SumoSNSTopic
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${TopicName}"
      Endpoint: !GetAtt SumoHTTPSource.SUMO_ENDPOINT
      Protocol: https
      DeliveryPolicy:
        healthyRetryPolicy:
          numRetries: 40
          minDelayTarget: 10
          maxDelayTarget: 300
          numMinDelayRetries: 3
          numMaxDelayRetries: 5
          numNoDelayRetries: 0
          backoffFunction: exponential


  SumoHTTPSource:
    Condition: install_http_logs_source
    Type: Custom::HTTPSource
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      Region: !Ref "AWS::Region"
      SourceName: !Ref HttpLogsSourceName
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceCategory: !Ref HttpLogsSourceCategoryName
      CollectorId: !GetAtt SumoHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      MessagePerRequest: true

